---
title: "HW6"
author: "Jiaheng Cai"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(KMsurv)
library(survival)
```

# 8.4

## (a)

```{r}
data(bnct)
bnct$z1 = ifelse(bnct$trt == 2, 1, 0)
bnct$z2 = ifelse(bnct$trt == 3, 1, 0)
fit.breslow = coxph(Surv(time, death) ~ z1 + z2, data = bnct, ties = "breslow")
fit.breslow
exp(confint(fit.breslow))
```
RR is 0.1633, CI is (0.0545, 0.4892)

## (b)
Overall idea
```{r}
summary(fit.breslow)
```
Score test
```{r}
round(cbind(fit.breslow$score, 1 - pchisq(fit.breslow$score, 2)), 4)
```

Likelihood test
```{r}
round(cbind(2*(fit.breslow$loglik[2]-fit.breslow$loglik[1]), 
            1-pchisq(2*(fit.breslow$loglik[2]-fit.breslow$loglik[1]), 2)), 4)
```

Wald test
```{r}
b.null <- c(0, 0)
X2.wald <- t(fit.breslow$coefficients[1:2] - b.null) %*% 
  solve(fit.breslow$var[-4, -4]) %*% 
  (fit.breslow$coefficients[1:2] - b.null)
round(cbind(X2.wald, 1-pchisq(X2.wald, 2)), 4)
```

## (c)
```{r}
C  <- c(1, -1)
b0 <- c(0, 0)
b  <- fit.breslow$coefficients
V  <- fit.breslow$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% C) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 2)), 4)
```

## (d)
```{r}
rr = exp(fit.breslow$coef[2]-fit.breslow$coef[1])
var = fit.breslow[["var"]][1,1]+fit.breslow[["var"]][2,2]-2*fit.breslow[["var"]][1,2]

exp(fit.breslow$coef[2]-fit.breslow$coef[1]-1.96*sqrt(var))
exp(fit.breslow$coef[2]-fit.breslow$coef[1]+1.96*sqrt(var))
```

## (e)(f)
```{r}
fit.breslow1 = coxph(Surv(time, death) ~ z1, data = bnct, ties = "breslow")
summary(fit.breslow1)
fit.breslow2 = coxph(Surv(time, death) ~ z2, data = bnct, ties = "breslow")
summary(fit.breslow2)
```

LL
```{r}
round(cbind(2*(fit.breslow1$loglik[2]-fit.breslow1$loglik[1]), 
            1-pchisq(2*(fit.breslow1$loglik[2]-fit.breslow1$loglik[1]), 1)), 4)
round(cbind(2*(fit.breslow2$loglik[2]-fit.breslow2$loglik[1]), 
            1-pchisq(2*(fit.breslow2$loglik[2]-fit.breslow2$loglik[1]), 1)), 4)
```

Wald
```{r}
C  <- c(1)
b0 <- c(0)
b  <- fit.breslow1$coefficients
V  <- fit.breslow1$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% C) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4)

C  <- c(1)
b0 <- c(0)
b  <- fit.breslow2$coefficients
V  <- fit.breslow2$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% C) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4)
```

# 8.5
## (a)
c2 = NHL Auto
c3 = HOD Allo
c4 = HOD Auto

```{r}
data(hodg)
hodg$c2 = rep(0,nrow(hodg))
hodg$c3 = rep(0,nrow(hodg))
hodg$c4 = rep(0,nrow(hodg))
hodg$c2[hodg$dtype == 1 & hodg$gtype == 2] = 1
hodg$c3[hodg$dtype == 2 & hodg$gtype == 1] = 1
hodg$c4[hodg$dtype == 2 & hodg$gtype == 2] = 1
```

gtypeb:
allo = 0
auto = 1

dtypeb:
NHL = 0
HOD = 1

int = gtypeb* dtypeb
```{r}
hodg$gtypeb = ifelse(hodg$gtype == 1,0,1)
hodg$dtypeb = ifelse(hodg$dtype == 1,0,1)
hodg$int = hodg$gtypeb* hodg$dtypeb
```

```{r}
fit.hodg = coxph(Surv(time, delta) ~ c2 + c3 + c4, data = hodg, ties = "breslow")
table = summary(fit.hodg)
table = cbind(table[["coefficients"]],table[["coefficients"]][,4]^2)
colnames(table)[6] = 'chisq'
table
```

Not sure, but put ANODE in this HW
```{r}
anova(fit.hodg)
```

## (b)
```{r}
fit.hodgb = coxph(Surv(time, delta) ~ gtypeb + dtypeb + int, data = hodg, ties = "breslow")
summary(fit.hodgb)
table = summary(fit.hodgb)
table = cbind(table[["coefficients"]],table[["coefficients"]][,4]^2)
colnames(table)[6] = 'chisq'
table
anova(fit.hodgb)
```

Wald
```{r}
C  <- c(0,0,1)
b0 <- c(0, 0,0)
b  <- fit.hodgb$coefficients
V  <- fit.hodgb$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% C) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4)
```

## (c)
```{r}
summary(fit.hodg)
```
c2 (NHL auto)    est=1.942    ci=(0.6427, 5.870)

## (d)
Allo group
```{r}
C  <- c(0,1,0)
b0 <- c(0, 0,0)
b  <- fit.hodg$coefficients
V  <- fit.hodg$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% C) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4)
```

auto group
```{r}
C  <- c(1,0,-1)
b0 <- c(0, 0,0)
b  <- fit.hodg$coefficients
V  <- fit.hodg$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% C) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4) #1 or 2 df?
```

## (e)
```{r}
C  <- rbind(c(1,0,0),c(0,1,-1))
b0 <- c(0, 0,0)
b  <- fit.hodg$coefficients
V  <- fit.hodg$var
wald = t(C %*% b - C %*% b0) %*% solve((C) %*% V %*% t(C)) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 2)), 4)
```

# 8.10
## (a)
```{r}
data(bmt)
fit.bmt = coxph(Surv(ta, da) ~ z10, data = bmt, ties = "breslow")
summary(fit.bmt)
```

## (b) ???
```{r}
(fit.group  <- coxph(Surv(ta, da) ~ factor(group) + z10, data = bmt, ties = 'breslow'))
fit.groupb  <- coxph(Surv(ta, da) ~ factor(group), data = bmt, ties = 'breslow')
```

```{r}
group.coef <- fit.group$coefficients

X2.lrt <- 2 * (fit.group$loglik[2] - fit.groupb$loglik[2])
round(cbind(X2.lrt, 1-pchisq(X2.lrt, 1)), 4)


C  <- c(0,0,1)
b0 <- c(0,0,0)
b  <- group.coef
V  <- fit.group$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% (C)) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4)
```

## (c)
```{r}
fit.bmtI = coxph(Surv(ta, da) ~ z10 + factor(group)+factor(group)*z10, data = bmt, ties = "breslow")
summary(fit.bmtI)

C  <- rbind(c(0,0,0,1,0),c(0,0,0,0,1))
b0 <- c(0,0,0,0,0)
b  <- fit.bmtI$coefficients
V  <- fit.bmtI$var
wald = t(C %*% b - C %*% b0) %*% solve((C) %*% V %*% t(C)) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 2)), 4)
```

## (d)
```{r}
fit.bmtd = coxph(Surv(ta, da) ~ z1 + z2+z1*z2+z3+z4+z3*z4+z5+z6+z5*z6+z8+z7+factor(group)+z10, data = bmt, ties = "breslow")
summary(fit.bmtd)
step(fit.bmtd)
```

```{r}
(best.fit = coxph(Surv(ta, da) ~ z1 + z6 + factor(group) + z10, 
    data = bmt, ties = "breslow"))
summary(best.fit)

C  <- c(0,0,0,0,1)
b0 <- c(0,0,0,0,0)
b  <- best.fit$coefficients
V  <- best.fit$var
wald = t(C %*% b - C %*% b0) %*% solve(t(C) %*% V %*% (C)) %*% 
  (C %*% b - C %*% b0)
round(cbind(wald, 1-pchisq(wald, 1)), 4)
```

# 8.14
## (a)
```{r}
fit.group  <- coxph(Surv(ta, da) ~ factor(group) + z10, data = bmt, ties = 'breslow')

b.haz <- basehaz(fit.group, centered = F)
t     <- b.haz[ ,2]
S.est <- cbind(exp(-b.haz[,1]), t)
b.est <- fit.group$coefficients

S1 <- S.est[,1]^(exp(t(b.est) %*% c(0, 0, 0)))
S2 <- S.est[,1]^(exp(t(b.est) %*% c(1, 0, 0)))
S3 <- S.est[,1]^(exp(t(b.est) %*% c(0, 1, 0)))
S4 <- S.est[,1]^(exp(t(b.est)%*% c(0, 0, 1)))
S5 <- S.est[,1]^(exp(t(b.est)%*% c(1, 0, 1)))
S6 <- S.est[,1]^(exp(t(b.est)%*% c(0, 1, 1)))

plot(S1 ~ t, type = 's', xlim = c(0, 3000), ylim = c(0.6, 1),
     main = 'Est. Survival Functions',
     ylab = 'Est. Survival Function', xlab = 'Time')
lines(S2 ~ t, type = 's', lty = 2, col = 2)
lines(S3 ~ t, type = 's', lty = 3, col = 3)
lines(S4 ~ t, type = 's', lty = 4, col = 4)
lines(S5 ~ t, type = 's', lty = 4, col = 4)
lines(S6 ~ t, type = 's', lty = 4, col = 4)
legend('bottomleft', 
       c('S1', 'S2', 'S3', 'S4','S5','S6'), 
       col = 1:4, lty = 1:4, bty = 'n', cex = .85)
```

## (b)
```{r}
fit.s1 <- survfit(fit.group, newdata = data.frame(group = 3, z10 = 0), 
                  se.fit = TRUE, conf.int = .95, conf.type = 'log-log')

summary(fit.s1)

fit.s2 <- survfit(fit.group, newdata = data.frame(group = 3, z10 = 1), 
                  se.fit = TRUE, conf.int = .95, conf.type = 'log-log')

summary(fit.s2)
```


