---
title: "HW7"
author: "Jiaheng Cai"
date: "11/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(KMsurv)
library(survival)
library(survMisc)
library(dplyr)
library(tidyverse)
```

## 8.12
```{r}
data(std)
std = std[-c(1)]
std$iinfct = as.factor(std$iinfct)
std$condom = as.factor(std$condom)
fit.std = coxph(Surv(time, rinfct) ~ ., data = std, ties = 'breslow')
summary(fit.std)
step(fit.std)
fit.std.f = coxph(Surv(time, rinfct) ~ yschool + iinfct + os30d + abdpain + 
                    condom + vagina + dchexam, data = std, ties = 'breslow')
summary(fit.std.f)
```

## 9.3
### a
```{r}
data(gastric)
fit.gas = coxph(Surv(time, event) ~ ., data = gastric, ties = 'breslow')
summary(fit.gas)
confint(fit.gas)
exp(confint(fit.gas))
```

### b
```{r}
event.times = sort(unique(gastric$time[gastric$event == 1]))
gastric2 = survSplit(data = gastric, cut = event.times, end = "time", 
                     start = 't0', event = "event")
gastric2$tdc = gastric2$group * log(gastric2$time)
fit.gast = coxph(Surv(t0, time, event) ~ group + tdc, data = gastric2, 
                 ties = 'breslow')
summary(fit.gast)
```
tdc /= 0 means nonproportional hazards

### c
```{r}
loglik = as.numeric(length(event.times))

for(i in 1:length(event.times)){
  gastric2$z1t = ifelse(gastric2$time <= event.times[i] & gastric2$group == 0, 1, 0)
  gastric2$z2t = ifelse(gastric2$time > event.times[i] & gastric2$group == 0, 1, 0)
  fit = coxph(Surv(t0, time, event) ~  z1t +z2t, data = gastric2, ties = 'breslow')
  loglik[i] = fit$loglik[2]
}

cbind(event.times, loglik)
opt_tau <- event.times[which.max(loglik)]
opt_tau
```

```{r}
gastric2$z1t = ifelse(gastric2$time <= 254 & gastric2$group == 0, 1, 0)
gastric2$z2t = ifelse(gastric2$time > 254 & gastric2$group == 0, 1, 0)
fit.gastric.f = coxph(Surv(t0, time, event) ~ z1t +z2t, data = gastric2, ties = 'breslow')
summary(fit.gastric.f)
```

treat patients with chemotherapy only have a lower relative risk in 0-245 days and a higher relative risk after 245 days

## 9.5
### a

```{r}
data(larynx)
larynx$sefi = ifelse(larynx$diagyr < 75, 0, 1) 

fit.l.s = coxph(Surv(time, delta) ~ factor(stage) + age + strata(sefi), data = larynx, ties = 'breslow')
fit.l = coxph(Surv(time, delta) ~ factor(stage) + age, data = larynx, ties = 'breslow')

larynx74 = larynx[larynx$diagyr < 75, ] 
larynx76 = larynx[larynx$diagyr >= 75, ]

fit0 = coxph(Surv(time, delta) ~ factor(stage) + age, data = larynx74, ties = 'breslow')
fit1 = coxph(Surv(time, delta) ~ factor(stage) + age, data = larynx76, ties = 'breslow')

summary(fit.l.s)
summary(fit.l)

anova(fit.l.s)
anova(fit.l)

```

### b
```{r}
X2 = -2*(fit.l.s$loglik[2] - (fit0$loglik[2] + fit1$loglik[2])); X2
1 - pchisq(X2, 4) 
```

### c ???
```{r}
W = (fit1$coefficients[1] - fit0$coefficients[1])^2 / (fit1$var[1,1] + fit0$var[1,1])
1 - pchisq(W, 1) 

W = (fit1$coefficients[2] - fit0$coefficients[2])^2 / (fit1$var[2,2] + fit0$var[2,2])
1 - pchisq(W, 1)

W = (fit1$coefficients[3] - fit0$coefficients[3])^2 / (fit1$var[3,3] + fit0$var[3,3])
1 - pchisq(W, 1)

W = (fit1$coefficients[4] - fit0$coefficients[4])^2 / (fit1$var[4,4] + fit0$var[4,4])
1 - pchisq(W, 1)
```

## 9.8
### a
```{r}
data(burn)
event.times = sort(unique(burn$T3[burn$D3 == 1]))
burn2 = survSplit(data = burn, cut = event.times,
                   end = "T3", start = 't0', event = "D3")
burn2$teti = ifelse(burn2$T3 >= burn2$T1 & burn2$D1 == 1, 1, 0)
fit.burn = coxph(Surv(t0, T3, D3) ~ D1+teti, data = burn2, ties = 'breslow')
summary(fit.burn)
```

### b
```{r}
burn2$tpti = ifelse(burn2$T3 >= burn2$T2 & burn2$D2 == 1, 1, 0)
fit.burn.p = coxph(Surv(T3, D3) ~ tpti + D2, data = burn2, ties = 'breslow')
summary(fit.burn.p)
```

### c
```{r}
fit.burn.f = coxph(Surv(t0, T3, D3) ~ Z1+Z2+Z3+Z4+Z5+Z6+Z7+Z8+Z9+Z10+as.factor(Z11)
                   +T1+teti+T2+tpti+D1+D2, data = burn2, ties = 'breslow')
summary(fit.burn.f)
```

### d
No non-propotion detected.
```{r}
burn3 = filter(burn2,burn2$D2==1)
fit.burn.f1 = coxph(Surv(t0, T3, D3) ~ Z1+Z2+Z3+Z4+Z5+Z6+Z7+Z8+Z9+Z10+
                      as.factor(Z11)+T1+teti+T2+tpti+D1, data = burn2, ties = 'breslow')
summary(fit.burn.f1)
```

## 11.1c
```{r}
data(larynx)
fit = coxph(Surv(time,delta) ~ as.factor(stage)+age, data = larynx, 
                method = 'breslow')

mg.residual = resid(fit, type = "martingale")
cs.residual = larynx$delta - mg.residual

fit.cs = survfit(Surv(cs.residual, larynx$delta) ~ 1) 
H.cs = cumsum(fit.cs$n.event/fit.cs$n.risk)
plot(fit.cs$time, H.cs, type='s', col='blue', 
     main = 'Cox-Snell Residual Plot', 
     xlab = 'Residual', ylab = 'Nelson-Aalen Cum. Hazard') 
abline(0, 1, col='red',  lty = 2)
```

## 11.3
### (a)
```{r}
data(larynx)
fit3 = basehaz(coxph(Surv(time,delta)~strata(as.factor(stage))+age, data = larynx, ties = 'breslow'))

plot(log(fit3$hazard[fit3$strata == 1])~ fit3$time[fit3$strata == 1], type = 's',
     ylab = 'Log Cumulative Hazard', xlab = 'Time', main = 'Log H(t) vs. Time',
     col = 'blue', lty = 1, xlim = c(0, 10), ylim = c(-4, 1))
lines(log(fit3$hazard[fit3$strata == 2]) ~  fit3$time[fit3$strata == 2],
      col = 'red', lty = 2, type = 's')
lines(log(fit3$hazard[fit3$strata == 3]) ~  fit3$time[fit3$strata == 3],
      col = 'yellow', lty = 2, type = 's')
lines(log(fit3$hazard[fit3$strata == 4]) ~  fit3$time[fit3$strata == 4],
      col = 'green', lty = 2, type = 's')
legend('bottomright', c('stage 1', 'stage 2', 'stage 3', 'stage 4'),col = c('blue', 'red', 'yellow', 'green'), lty = c(1, 4),
       bty = 'n')
```

### b
```{r}
  H1 = fit3$hazard[fit3$strata == 1]
  t1 = fit3$time[fit3$strata == 1]
  H2 = fit3$hazard[fit3$strata == 2]
  t2 = fit3$time[fit3$strata == 2]
  H3 = fit3$hazard[fit3$strata == 3]
  t3 = fit3$time[fit3$strata == 3]
  H4 = fit3$hazard[fit3$strata == 4]
  t4 = fit3$time[fit3$strata == 4]


plot((log(H2)-log(H1[1:15]))~ t2, type = 's',
     ylab = 'Log Cumulative Hazard', xlab = 'Time', main = 'Log H(t) vs. Time',
     col = 'blue', lty = 1, xlim = c(0, 10), ylim = c(-3, 3))
lines((log(H3)-log(H1[1:23])) ~  t3,
      col = 'brown', lty = 3, type = 's')
lines((log(H4)-log(H1[1:12])) ~  t4,
      col = 'green', lty = 4, type = 's')
legend('bottomright', c('stage 2-stage 1', 'stage 3-stage 1', 'stage 4-stage 1'),
       col = c('blue', 'brown', 'green'), lty = c(1:3),
       bty = 'n')
```


### c
```{r}
reptime <- function(l, t){
  x <- numeric(max(t))
  for(i in min(t):max(t)){
    diff <- i - t
    diff <- diff[diff >= 0]
    x[i] <- l[which.min(diff)]
  }
  return(x)
}

H1 <- fit3$hazard[fit3$strata == 1]
H2 <- fit3$hazard[fit3$strata == 2]
H3 <- fit3$hazard[fit3$strata == 3]
H4 <- fit3$hazard[fit3$strata == 4]

t1 <- fit3$time[fit3$strata == 1]
t2 <- fit3$time[fit3$strata == 2]
t3 <- fit3$time[fit3$strata == 3]
t4 <- fit3$time[fit3$strata == 4]


H1 <- reptime(H1, t1)
H2 <- reptime(H2, t2)
H3 <- reptime(H3, t3)
H4 <- reptime(H4, t4)

plot(H2[1:9] ~ H1[1:9], type = 's',
     ylab = 'Log Hazard', xlab = 'Stage 1', main = 'Anderson Plot',
     col = 'blue', lty = 1, xlim = c(0, 1), ylim = c(0, 2))
lines(H3 ~ H1,
      col = 'red', lty = 2, type = 's')
lines(H4[1:4] ~ H1[1:4],
      col = 'green', lty = 3, type = 's')
legend('bottomright', c('stage 2', 'stage 3', 'stage 4'),
       col = c('blue', 'red', 'green'), lty = c(1:3),
       bty = 'n')
abline(0, 1, col='black',  lty=3)
```








